/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ListingsSlugRouteImport } from './routes/listings.$slug'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSavedRouteImport } from './routes/dashboard.saved'
import { Route as DashboardReviewsRouteImport } from './routes/dashboard.reviews'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardListingsRouteImport } from './routes/dashboard.listings'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as DashboardArticlesRouteImport } from './routes/dashboard.articles'
import { Route as DashboardAddListingRouteImport } from './routes/dashboard.add-listing'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminListingsRouteImport } from './routes/admin.listings'
import { Route as AdminClaimsRouteImport } from './routes/admin.claims'
import { Route as AdminArticlesRouteImport } from './routes/admin.articles'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ListingsSlugRoute = ListingsSlugRouteImport.update({
  id: '/listings/$slug',
  path: '/listings/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSavedRoute = DashboardSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardListingsRoute = DashboardListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardArticlesRoute = DashboardArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAddListingRoute = DashboardAddListingRouteImport.update({
  id: '/add-listing',
  path: '/add-listing',
  getParentRoute: () => DashboardRoute,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticlesRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListingsRoute = AdminListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClaimsRoute = AdminClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/articles': typeof ArticlesRouteWithChildren
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/dashboard/add-listing': typeof DashboardAddListingRoute
  '/dashboard/articles': typeof DashboardArticlesRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/listings': typeof DashboardListingsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/saved': typeof DashboardSavedRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/listings/$slug': typeof ListingsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/dashboard/add-listing': typeof DashboardAddListingRoute
  '/dashboard/articles': typeof DashboardArticlesRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/listings': typeof DashboardListingsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/saved': typeof DashboardSavedRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/listings/$slug': typeof ListingsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/articles': typeof ArticlesRouteWithChildren
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/dashboard/add-listing': typeof DashboardAddListingRoute
  '/dashboard/articles': typeof DashboardArticlesRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/listings': typeof DashboardListingsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/saved': typeof DashboardSavedRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/listings/$slug': typeof ListingsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/articles'
    | '/auth'
    | '/categories'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/pricing'
    | '/reset-password'
    | '/search'
    | '/admin/articles'
    | '/admin/claims'
    | '/admin/listings'
    | '/admin/settings'
    | '/admin/users'
    | '/articles/$slug'
    | '/dashboard/add-listing'
    | '/dashboard/articles'
    | '/dashboard/billing'
    | '/dashboard/listings'
    | '/dashboard/notifications'
    | '/dashboard/reviews'
    | '/dashboard/saved'
    | '/dashboard/settings'
    | '/listings/$slug'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/articles'
    | '/auth'
    | '/categories'
    | '/contact'
    | '/forgot-password'
    | '/pricing'
    | '/reset-password'
    | '/search'
    | '/admin/articles'
    | '/admin/claims'
    | '/admin/listings'
    | '/admin/settings'
    | '/admin/users'
    | '/articles/$slug'
    | '/dashboard/add-listing'
    | '/dashboard/articles'
    | '/dashboard/billing'
    | '/dashboard/listings'
    | '/dashboard/notifications'
    | '/dashboard/reviews'
    | '/dashboard/saved'
    | '/dashboard/settings'
    | '/listings/$slug'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/articles'
    | '/auth'
    | '/categories'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/pricing'
    | '/reset-password'
    | '/search'
    | '/admin/articles'
    | '/admin/claims'
    | '/admin/listings'
    | '/admin/settings'
    | '/admin/users'
    | '/articles/$slug'
    | '/dashboard/add-listing'
    | '/dashboard/articles'
    | '/dashboard/billing'
    | '/dashboard/listings'
    | '/dashboard/notifications'
    | '/dashboard/reviews'
    | '/dashboard/saved'
    | '/dashboard/settings'
    | '/listings/$slug'
    | '/admin/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArticlesRoute: typeof ArticlesRouteWithChildren
  AuthRoute: typeof AuthRoute
  CategoriesRoute: typeof CategoriesRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  ListingsSlugRoute: typeof ListingsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/listings/$slug': {
      id: '/listings/$slug'
      path: '/listings/$slug'
      fullPath: '/listings/$slug'
      preLoaderRoute: typeof ListingsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/saved': {
      id: '/dashboard/saved'
      path: '/saved'
      fullPath: '/dashboard/saved'
      preLoaderRoute: typeof DashboardSavedRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reviews': {
      id: '/dashboard/reviews'
      path: '/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof DashboardReviewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/listings': {
      id: '/dashboard/listings'
      path: '/listings'
      fullPath: '/dashboard/listings'
      preLoaderRoute: typeof DashboardListingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/articles': {
      id: '/dashboard/articles'
      path: '/articles'
      fullPath: '/dashboard/articles'
      preLoaderRoute: typeof DashboardArticlesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/add-listing': {
      id: '/dashboard/add-listing'
      path: '/add-listing'
      fullPath: '/dashboard/add-listing'
      preLoaderRoute: typeof DashboardAddListingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listings': {
      id: '/admin/listings'
      path: '/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AdminListingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/claims': {
      id: '/admin/claims'
      path: '/claims'
      fullPath: '/admin/claims'
      preLoaderRoute: typeof AdminClaimsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminArticlesRoute: typeof AdminArticlesRoute
  AdminClaimsRoute: typeof AdminClaimsRoute
  AdminListingsRoute: typeof AdminListingsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArticlesRoute: AdminArticlesRoute,
  AdminClaimsRoute: AdminClaimsRoute,
  AdminListingsRoute: AdminListingsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ArticlesRouteChildren {
  ArticlesSlugRoute: typeof ArticlesSlugRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesSlugRoute: ArticlesSlugRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAddListingRoute: typeof DashboardAddListingRoute
  DashboardArticlesRoute: typeof DashboardArticlesRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardListingsRoute: typeof DashboardListingsRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardReviewsRoute: typeof DashboardReviewsRoute
  DashboardSavedRoute: typeof DashboardSavedRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAddListingRoute: DashboardAddListingRoute,
  DashboardArticlesRoute: DashboardArticlesRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardListingsRoute: DashboardListingsRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardReviewsRoute: DashboardReviewsRoute,
  DashboardSavedRoute: DashboardSavedRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ArticlesRoute: ArticlesRouteWithChildren,
  AuthRoute: AuthRoute,
  CategoriesRoute: CategoriesRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  ListingsSlugRoute: ListingsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
